accepted = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "IJG",
  "NCSA",
  "ISC",
  "Zlib",
  "MPL-2.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "Unlicense",
  "BSL-1.0",
]

ignore-build-dependencies = false
ignore-dev-dependencies = false
